language: go

before_install:
  - go get -u github.com/Masterminds/glide

script:
  - glide install
  # - go test -v

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash